config/routes.rb
Rails.application.routes.draw do

  resources :comments, only: [:create, :edit, :update, :new]
  resources :events do
    resources :locations, only: :show
  end
  resources :users, only: [:new, :create, :show, :edit, :update, :destroy] do
      resources :events
      resources :locations
    end
  resources :rsvps, only: [:create, :destroy, :index]

  resources :locations, only: :show

  root 'static_pages#home'

  get '/auth/facebook/callback' => 'sessions#create'
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :location
  has_many :rsvps, dependent: :destroy
  has_many :users, through: :rsvps
  has_many :comments

  accepts_nested_attributes_for :location
  accepts_nested_attributes_for :rsvps

  validates :title, :description, :date, :time, presence: true
  validate :event_date_cannot_be_in_the_past

  def event_date_cannot_be_in_the_past
    if self.date.present? && self.date < Date.today
     errors.add(:past_date, "Event can't be in the past")
   end
  end

  def self.most_recent(limit)
    order("created_at desc").limit(limit)
  end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def new
    @event = Event.new
    @event.build_location(session[:location])
  end

  def create
    @event = Event.new(event_params)
    @event.location = find_or_create_location
    if @event.save
      Rsvp.create(user_id: params[:event][:user_id], event_id: @event.id)
      redirect_to user_event_path(@event.user, @event)
    else
      render 'new'
    end
  end

  def edit
    @event = Event.find_by(id: params[:id])
  end

  def update
    @event = Event.find_by(id: params[:id])
    if @event.update(event_params)
      redirect_to user_event_path(@event.user, @event)
    else
      render 'edit'
    end
  end

  def destroy
    Event.find(params[:id]).destroy
    redirect_to user_path(current_user)
  end

  def index
    date_range  = Date.today..(Date.today+7)
    @events = Event.all.sort_by {|event| event.date}
    @recent_events = Event.most_recent(5)
    respond_to do |format|
       format.html { render :index }
       format.json { render json: @events }
    end
  end

  def show
    @event = Event.find_by(id: params[:id])
    @comment = Comment.new
    respond_to do |format|
       format.html { render :show }
       format.json { render json: @event }
    end

  end

private


  def event_params
  params.require(:event).permit(
    :title,
    :date,
    :time,
    :description,
    :user_id,
    location_attributes: [
      :name,
      :address,
      :city,
      :state,
      :public,
      :user_id
    ],
    rsvp_attributes: [:user_id])
  end

  def find_or_create_location
    location = Location.find_or_create_by(
      name: params[:event][:location_attributes][:name],
      address: params[:event][:location_attributes][:address],
      city: params[:event][:location_attributes][:city],
      state: params[:event][:location_attributes][:state],
      public: params[:event][:location_attributes][:public],
      user_id: params[:event][:location_attributes][:user_id]
    )
  end
end

app/views/events/_form.html.erb
<%= form_for [:user, @event] do |f| %>

<div class="form-group">
<%= f.label "Event Title" %>
<br>
<%= f.text_field :title, class: "form-control", :placeholder => (@event.errors.full_messages_for(:title).first) || @event.title%>
</div>

<div class="form-group">
  <%= f.label :date, "Date" %>
  <br>
  <%= f.date_select :date , class: "form-control", start_year: Time.now.year, order: [:month, :day, :year], prompt: { day: 'Select day', month: 'Select month', year: 'Select year' }%>
</div>

  <div class="form-group">
    <%= f.label :time, "Time" %>
    <br>
    <%= f.time_select :time, class: "form-control", minute_step: 15, ampm: true%>
  </div>

  <div class="form-group">
  <%= f.label "Description" %>
  <br>
  <%= f.text_area :description, class: "form-control", :placeholder => (@event.errors.full_messages_for(:description).first) || @event.description%>
  </div>

  <%= f.hidden_field :user_id, value: current_user.id %>

<p>Location</p>
  <%= f.fields_for :location do |f| %>
    <%= f.label :name%>
    <br>
    <%= f.text_field :name, class: "form-control", :placeholder => (@event.location.errors.full_messages_for(:name).first) || @event.location.name%><br>

    <%= f.label :address %>
    <br>
    <%= f.text_field :address, class: "form-control", :placeholder => (@event.location.errors.full_messages_for(:address).first) || @event.location.address%><br>

    <%= f.label :city %>
    <br>
    <%= f.text_field :city,class: "form-control", :placeholder => (@event.location.errors.full_messages_for(:city).first) || @event.location.city %><br>

    <%= f.label :state %>
    <br>
    <%= f.select :state, us_states, :prompt => 'Select One' %>
    <br>

    <div class="mt-4">
      <%= f.label "Is this location public?" %> &nbsp;&nbsp
      <%= f.check_box :public %>&nbsp Yes
    </div>
    <br>
      <%= f.hidden_field :user_id, value: current_user.id %>
  <% end %>

  <div class="actions">
    <br/>
        <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>


<% end %>

app/views/events/edit.html.erb
<div class="row">
  <div class="col-sm-6 mx-auto pt-5">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title pb-3 text-center">Edit <%=@event.title.titleize%></h5>
        <% if @event.errors.any? %>
          <div id="error_explanation">
            <table class="table table-borderless">
              <tbody>
                <% @event.errors.full_messages.each do |msg| %>
                  <tr class="table-danger"><td>&nbsp &nbsp <%= msg %></td></tr>
                <% end %>
              </tbody>
            </table>
          </div>
        <% end %>
        <%= render 'form' %>
          <%= form_tag user_event_path(current_user, @event), method: "delete" do -%>
            <div><%= submit_tag 'Delete Event', class: 'btn btn-link mt-3' %></div>
          <% end -%>
        </div>
      </div>
    </div>
  </div>

app/views/events/index.html.erb
<div class="row">
  <div class="col-sm-10 mx-auto pt-5">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title pb-3 text-center">Upcoming Events</h5>
        <table class="table table-dark">
          <thead>
            <tr>
              <th scope="col"></th>
              <th scope="col">Name</th>
              <th scope="col">Location</th>
              <th scope="col">Date</th>
            </tr>
          </thead>
          <tbody>
          <%@events.each do |event|%>
            <tr>
             <th scope="row"></th>
             <td><%=link_to event.title.titleize, user_event_path(event.user, event)%></td>
             <td><%=event.location.city.titleize%>, <%=event.location.state.titleize%></td>
             <td><%=event.date%></td>
           </tr>
         <%end%>
       </tbody>
      </table>
      <%= link_to '<button type="button" class="col-sm-8 mx-auto btn btn-primary btn-lg btn-block">Create New Event</button>'.html_safe, new_user_event_path(current_user) %>
      </div>
    </div>
    <div class="col-sm-12 mx-auto pt-5">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title pb-3 text-center">Recently Added</h5>
          <table class="table table-dark">
            <thead>
              <tr>
                <th scope="col"></th>
                <th scope="col">Name</th>
                <th scope="col">Location</th>
                <th scope="col">Date</th>
              </tr>
            </thead>
            <tbody>
            <%@recent_events.each do |event|%>
              <tr>
               <th scope="row"></th>
               <td><%=link_to event.title.titleize, user_event_path(event.user, event)%></td>
               <td><%=event.location.city.titleize%>, <%=event.location.state.titleize%></td>
               <td><%=event.date%></td>
             </tr>
           <%end%>
         </tbody>
        </table>
      </div>
    </div>
  </div>

app/views/events/new.html.erb
<div class="row">
  <div class="col-sm-8 mx-auto pt-5">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title pb-3 text-center">Create an Event</h5>
          <% if @event.errors.any? %>
            <div id="error_explanation">
              <table class="table table-borderless">
                <tbody>
                  <% @event.errors.full_messages.each do |msg| %>
                    <tr class="table-danger"><td>&nbsp &nbsp <%= msg %></td></tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          <% end %>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="row">
  <div class="col-sm-6 mx-auto pt-5">
    <div class="card mb-3">
      <div class="card-body">
        <h5 class="card-title pb-3">Event: <%=@event.title%></h5>
          <p>Created By: <%=link_to @event.user.name, user_path(@event.user)%></p>
          <p>Description: <%=@event.description%></p>
          <p>Date: <%=@event.date.strftime("%A, %B %-d, %Y" )%></p>
          <p>Time: <%=@event.time.strftime("%-l:%M%P")%></p>
          <p>Location:</p>
          <p>
            <%=link_to @event.location.name, event_location_path(@event, @event.location)%><br>
            <%=@event.location.address%><br>
            <%=@event.location.city%>, <%=@event.location.state%>
            </p>
          <%if @event.user == current_user%>
            <%= link_to "Edit Event", edit_user_event_path(current_user, @event), class:"btn btn-primary" %>
          <%end%>
      </div>
    </div>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title pb-3">Going: </h5>
          <ul class="list-group">
            <%@event.rsvps.each do |rsvp| %>
              <li class="list-group-item"><%=link_to rsvp.user.name, user_path(rsvp.user)%></li>
            <%end%>
          </ul>
          <%if @event.rsvps.detect {|r| r.user_id == current_user.id} == nil%>
            <%= button_to "Attend Event", rsvps_path, :method => :post, params: { "event_id" => @event.id }, class: "btn btn-primary mt-2" %>
          <%else%>
            <p>you are attending this event</p>
            <%= button_to "Unattend Event", rsvp_path, :method => :delete, class: "btn btn-outline-warning mt-2" %>
          <%end%>
      </div>
    </div>
  </div>
  <div class="col-sm-6 mx-auto pt-5">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title pb-3">Comments </h5>
          <%if @event.comments.empty?%>
            <p>There are no comments for this event</p>
          <%else%>
            <ul class="list-group" id="comment-list">
              <%@event.comments.each do |c| %>
                <li class="list-group-item"> <%=link_to c.user.name.titleize, user_path(c.user)%>: <%=c.content.capitalize%> <%=link_to "edit", edit_comment_path(c) if c.user == current_user%></li>
              <%end%>
            </ul>
          <%end%>
          <%if @event.rsvps.detect {|r| r.user == current_user}%>
            <p class="mt-4">Leave a Comment:</p>
            <%= render 'comments/comment_form' %>
          <%end%>
      </div>
    </div>
  </div>
</div>