config/routes.rb
Rails.application.routes.draw do

  resources :comments, only: [:create, :edit, :update, :new]
  resources :events do
    resources :locations, only: :show
  end
  resources :users, only: [:new, :create, :show, :edit, :update, :destroy] do
      resources :events
      resources :locations
    end
  resources :rsvps, only: [:create, :destroy, :index]

  resources :locations, only: :show

  root 'static_pages#home'

  get '/auth/facebook/callback' => 'sessions#create'
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :events, dependent: :destroy
  has_many :users, through: :events
  belongs_to :user

  validates :name, :address, :city, :state, presence: true

  scope :public_locations, -> { where(public: true) }
   scope :nearby, ->(city, state) { where("city = ? AND state = ?", city, state) }
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def show
    @location = Location.find_by(id: params[:id])
    session[:location] = @location
    respond_to do |format|
       format.html { render :show }
       format.json { render json: @location }
    end
  end

  def index
    @public_locations_nearby = Location.public_locations.nearby(current_user.city, current_user.state)
    @user_locations = Location.belong_to_user(current_user)
  end

  def new
    @location = Location.new

  end

  def create
    @location = Location.new(location_params)
    if @location.save
      redirect_to user_location_path(@location.user, @location)
    else
      render 'new'
    end
  end

  def edit
    @location = Location.find_by(id: params[:id])
  end

  def update
    @location = Location.find_by(id: params[:id])
    if @location.update(location_params)
      redirect_to user_location_path(@location.user, @location)
    else
      render 'edit'
    end
  end

  def destroy
    Location.find_by(id: params[:id]).destroy
    redirect_to user_path(current_user)
  end


  private

  def upcoming_events(location)
    location.events.find_all {|event| event.date > Date.today}
  end

  def location_params
  params.require(:location).permit(
      :name,
      :address,
      :city,
      :state,
      :public,
      :user_id
      )
  end

end

app/views/locations/_form.html.erb
<%= form_for [:user, @location] do |f| %>

<div class="form-group">
<%= f.label :name%>
<br>
<%= f.text_field :name, class: "form-control", :placeholder => (@location.errors.full_messages_for(:name).first) || @location.name%><br>
</div>

<div class="form-group">
  <%= f.label :address %>
  <br>
  <%= f.text_field :address, class: "form-control", :placeholder => (@location.errors.full_messages_for(:address).first) || @location.address%>
</div>

  <div class="form-group">
    <%= f.label :city %>
    <br>
    <%= f.text_field :city, class: "form-control", :placeholder => (@location.errors.full_messages_for(:city).first) || @location.city %>
  </div>

  <div class="form-group">
  <%= f.label :state %>
  <br>
  <%= f.select :state, us_states, :prompt => 'Select One' %>
  </div>

  <div class="form-group">
  <%= f.label "Is this location public?" %> &nbsp;&nbsp <%= f.check_box :public %>&nbsp Yes
  </div>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <div class="actions">
    <br/>
        <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/locations/edit.html.erb
<div class="row">
  <div class="col-sm-6 mx-auto pt-5">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title pb-3 text-center">Edit <%=@location.name.titleize%></h5>
        <% if @location.errors.any? %>
          <div id="error_explanation">
            <table class="table table-borderless">
              <tbody>
                <% @location.errors.full_messages.each do |msg| %>
                  <tr class="table-danger"><td>&nbsp &nbsp <%= msg %></td></tr>
                <% end %>
              </tbody>
            </table>
          </div>
        <% end %>
        <%= render 'form' %>
          <%= form_tag user_location_path(current_user, @location), method: "delete" do -%>
            <div><%= submit_tag 'Delete Location', class: 'btn btn-link mt-3' %></div>
          <% end -%>
        </div>
      </div>
    </div>
  </div>

app/views/locations/index.html.erb
<div class="row">
  <div class="col-sm-10 mx-auto pt-5">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title pb-3 text-center">Your Locations</h5>
        <table class="table table-dark">
          <thead>
            <tr>
              <th scope="col"></th>
              <th scope="col">Name</th>
              <th scope="col">Address</th>
              <th scope="col">City, State</th>
            </tr>
          </thead>
          <tbody>
          <%@user_locations.each do |location|%>
            <tr>
             <th scope="row"></th>
             <td><%=link_to location.name.titleize, user_location_path(location.user, location)%></td>
             <td><%=location.address.titleize%></td>
             <td><%=location.city.titleize%>, <%=location.state.titleize%></td>
           </tr>
         <%end%>
       </tbody>
      </table>
          <%= link_to '<button type="button" class="col-sm-8 mx-auto btn btn-primary btn-lg btn-block">Create New Location</button>'.html_safe, new_user_location_path(current_user) %>
    </div>
  </div>
<div class="col-sm-12 mx-auto pt-5">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title pb-3 text-center">Public Locations Nearby</h5>
        <table class="table table-dark">
          <thead>
            <tr>
              <th scope="col"></th>
              <th scope="col">Name</th>
              <th scope="col">Address</th>
              <th scope="col">City, State</th>
            </tr>
          </thead>
        <tbody>
          <%@public_locations_nearby.each do |location|%>
            <tr>
             <th scope="row"></th>
             <td><%=link_to location.name.titleize, user_location_path(location.user, location)%></td>
             <td><%=location.address.titleize%></td>
             <td><%=location.city.titleize%>, <%=location.state.titleize%></td>
           </tr>
          <%end%>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/locations/new.html.erb
<div class="row">
  <div class="col-sm-8 mx-auto pt-5">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title pb-3 text-center">Add a Location</h5>
          <% if @location.errors.any? %>
            <div id="error_explanation">
              <table class="table table-borderless">
                <tbody>
                  <% @location.errors.full_messages.each do |msg| %>
                    <tr class="table-danger"><td>&nbsp &nbsp <%= msg %></td></tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          <% end %>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/locations/show.html.erb
<div class="row">
  <div class="col-sm-6 mx-auto pt-5">
    <div class="card mb-3">
      <div class="card-body">
        <h5 class="card-title pb-3"><%=@location.name%></h5>
        <p>
          <%=@location.name%><br>
          <%=@location.address%><br>
          <%=@location.city%>, <%=@location.state%>
        </p>
        <%if @location.user == current_user%>
          <%= link_to '<button type="button" class="btn btn-primary mt-2">Edit Location</button>'.html_safe, edit_user_location_path(@location.user, @location) %>
        <%end%>
      </div>
    </div>
    <div id="event_details_div">
      <!--  for event details -->
    </div>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title pb-3">Upcoming Events: </h5>
        <p>Click on event for more details</p>
          <span class="clickable"><ul class="list-group pb-3 list-holder" id="upcoimng_events" data-id="<%=@location.id%>" data-user="<%=@location.user_id%>"></ul></span>
         <%if @location.public == true%>
           <%= link_to '<button type="button" class="btn btn-primary mt-2">Create New Event</button>'.html_safe, new_user_event_path(current_user) %>
         <%end%>
      </div>
    </div>
  </div>
</div>