config/routes.rb
Rails.application.routes.draw do

  resources :comments, only: [:create, :edit, :update, :new]
  resources :events do
    resources :locations, only: :show
  end
  resources :users, only: [:new, :create, :show, :edit, :update, :destroy] do
      resources :events
      resources :locations
    end
  resources :rsvps, only: [:create, :destroy, :index]

  resources :locations, only: :show

  root 'static_pages#home'

  get '/auth/facebook/callback' => 'sessions#create'
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
end

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <title>Eventime</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="/">Eventime</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <%if !current_user%>
            <a class="navbar-brand ml-3" href="<%= new_user_path %>"/>Sign Up</a>
            <a class="navbar-brand ml-3" href="<%= login_path %>"/>Log In</a>
          <%end%>
          <%if current_user%>
          <a class="navbar-brand ml-3" href="<%= user_path(current_user) %>"/><%=current_user.name.titleize%>'s Profile</a>
          <a class="navbar-brand ml-3" href="<%= events_path %>"/>Events</a>
          <a class="navbar-brand ml-3" href="<%= user_locations_path(current_user) %>"/>Locations</a>
            <%= button_to 'Logout', logout_path, :method => :delete, class: "btn btn-outline-warning btn-sm"%>
          <%end%>
      </div>
    </div>
  </nav>
    <div class="container main-box"  role="main">
        <%= yield %>
    </div>
  </body>
</html>